cesanta/fossa

fossa.c, src/net.c, src/resolv.c
This is the same changes as last time but in the right place this time (hopefully).
=> Fix coverity issues: close socket, close fp, free memory.

fossa.c, src/http.c
See https://groups.google.com/forum/#!topic/mongoose-users/vPP7AwVaFSA for background.
=> Fix overflowi in ns_send_websocket_handshake

fossa.c, src/iobuf.c
=> Revert "Backport simple iobuf allocation from V7"

fossa.c, src/iobuf.c
=> Revert "Revert "Backport simple iobuf allocation from V7""

src/net.c
Use getaddrinfo if available instead gethostbyname
=> Equal as https://github.com/cesanta/mongoose/pull/463

fossa.c, fossa.h, src/coap.c, src/coap.h, test/unit_test.c
Hi, Marko.
CoAP implementation, part 2: packet composer & unit-tests 
Please, make review.
BTW, `coap_add_uint16` function makes me crazy =)
=> CoAP composer

fossa.c
Amalgamate fossa.c after PR #202
=> Amalgamate fossa.c

fossa.c, fossa.h, src/coap.c, src/coap.h, test/unit_test.c
Hi, @mmikulicic !
Please, review this PR. 
Since this is my first protocol added to fossa, I'm not sure that I'm right in details.
Please, take a look. (aka PTAL)
=> coap minimal

fossa.c, fossa.h, src/coap.c, src/coap.h, test/unit_test.c
Added unit_tests & `/* LCOV_EXCL_LINE */` to increase coverage.
=> Increase CoAP coverage

fossa.c, src/coap.c, test/unit_test.c
Also change test listening port to reduce likelyhood of local conflicts
and add assertion to avoid surprising segfault if the port is already in use.
---
Hi @alashkin, I'd like you to do a small code review.
=> Fix OOB in COAP, closes #217

examples/coap_client/Makefile, examples/coap_client/coap_client.c, examples/coap_server/Makefile, examples/coap_server/coap_server.c
Hi, @mmikulicic!
This is last PR for CoAP minimal.
Added two standard protocol samples: coap_client & coap_server.
Next PRs (if any) will be some kind of additions (depends on discussion on document I'm going to write).
=> Add CoAP examples

examples/restful_server/restful_server.c, fossa.c, src/net.c
Hi @alashkin , please make a review:
Generated doc:
https://circle-artifacts.com/gh/cesanta/fossa/643/artifacts/0/home/ubuntu/fossa/docs/index.html#_ns_set_ssl
=> Document ns_set_ssl(). SSLlize resftul_server

apps/load_balancer/load_balancer.c
I'm using this as part of the dogfooding effort: tampermonkey script on slack needs ssl access. With this I can proxy http://oncall.cesanta.com via a local https://oncall.cesanta.com:8000 (with `127.0.0.1       localhost oncall.cesanta.com` in /etc/hosts)
=> Add SSL support for load_balancer app

examples/restful_server/Makefile, examples/restful_server/index.html
Hi @alashkin , please make a review!
To test, clone krypto repo, and then
cd examples/restful_server
make clean all SSL=krypton
./restful_server -s ../../test/server.pem
Point your browser to https://127.0.0.1:8000
=> Add SSL targets to restful server

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/235)
=> Amend Cesanta links

fossa.c, src/http.c, test/unit_test.c
Fix #239
Hi @alashkin , please make a review
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/241)
=> Send post_data in ns_connect_http()

fossa.h, src/common.h, test/unit_test.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/242)
=> Format. Add comment about _MSC_VER

fossa.c, fossa.h, src/net.c, src/net.h, src/util.c, src/util.h, test/unit_test.c
Hi @alashkin , please make a review
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/244)
=> Add ns_check_ip_acl() API call (for #237)

README.md, fossa.c, fossa.h, src/common.h, src/http.c, test/data/range.txt, test/unit_test.c
DIFFTEST=246
Refactored unit test a little, and done some yak shaving.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/247)
=> Add Range: header support (#237)

fossa.c, src/http.c, test/unit_test.c
Also, fix possible leak in http handler.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/248)
=> Add JS sorting to directory listing

fossa.c, fossa.h, src/coap.c, src/common.h, src/dns.c, src/http.c, src/internal.h, src/md5.c, src/net.c, src/net.h, src/resolv.c, src/util.c, src/util.h
Hi, @mmikulicic 
Ready to run fossa on Arduino Mega?
Please, make this review of this chaotic PR. 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/250)
=> Fix portability for Arduino Mega

examples/restful_server/Makefile, examples/restful_server/restful_server.c, fossa.c, fossa.h, src/common.h, src/http.c, src/http.h, test/data/cgi/index.cgi, test/unit_test.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/251)
=> Add CGI functionality

fossa.c, fossa.h, src/http.c, src/http.h, test/unit_test.c
Format is the same as accepted by Mongoose in EXTRA_MIME_TYPES.
Closes #238.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/255)
=> Add an option for overriding Content-Type

fossa.c, src/util.c, test/unit_test.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/256)
=> Fix ns_vcmp and ns_casecmp

fossa.c, src/http.c
Replicating https://github.com/cesanta/mongoose/commit/773efb074585b8001eeb68807840c3194fca9951 in fossa
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/258)
=> Respect client WEBSOCKET_OP_CLOSE

fossa.c, src/http.c
Addresses https://github.com/cesanta/mongoose/issues/489
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/259)
=> Trim leading spaces in CGI interpreter

fossa.c, src/http.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/260)
=> Fix old clang-format artifact

apps/load_balancer/load_balancer.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/261)
=> Amend load_balancer usage string

Makefile, examples/arduino_restful_server/Makefile, examples/arduino_restful_server/arduino_restful_server.ino, fossa.c, fossa.h, platforms/arduino_common/avrdebug.cpp, platforms/arduino_common/avrdebug.h, platforms/arduino_common/avrlibc_compat.cpp, platforms/arduino_common/avrlibc_compat.h, platforms/arduino_ethernet_W5100/Makefile, platforms/arduino_ethernet_W5100/avrsupport.cpp, platforms/arduino_ethernet_W5100/avrsupport.h, platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, platforms/arduino_ethernet_W5100/src/W5100_sockets.h, src/Makefile, src/common.h, src/internal.h, src/net.c
Hi, @rojer 
Please, review this PR.
It implements support of Arduino Ethernet Shield (W5100) for fossa.
Note: avrsupport.h & avrsupport.cpp is just an amalgamation of avrdebug, avrlibc_compat and W5100_sockets files.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/262)
=> Add Arduino (W5100) support

Makefile, apps/api_server/api_server.c, apps/load_balancer/load_balancer.c, platforms/arduino_ethernet_W5100/avrsupport.cpp
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/267)
=> Format 'apps' too and reformat everything

examples/arduino_restful_server/arduino_restful_server.ino, platforms/arduino_common/avrdebug.cpp, platforms/arduino_common/avrlibc_compat.h, platforms/arduino_ethernet_W5100/avrsupport.cpp, platforms/arduino_ethernet_W5100/avrsupport.h, platforms/arduino_ethernet_W5100/src/W5100_sockets.h, platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/Adafruit_CC3000.cpp, platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/Adafruit_CC3000_Server.cpp, platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/library.properties, platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/cc3000_common.h, platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/sntp.cpp, platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.h, platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp, platforms/arduino_wifi_CC3000/src/CC3000_utils.h
Hi, @rojer 
Please, review this PR.
It is support of CC3000 for fossa (only server - aka restful_server).
This code is based on Adafruit/Texas instruments library (https://github.com/adafruit/Adafruit_CC3000_Library)
Library stores in fossa's rep unformatted (so, sometimes code style could be strange). Later I'll make an amalgamation and use clang-format against it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/268)
=> Add support of CC3000 (server)

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/271)
=> Add CoAP to the README

fossa.c, fossa.h, platforms/arduino_ethernet_W5100/avrsupport.cpp, platforms/arduino_ethernet_W5100/avrsupport.h, platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp, src/net.c, src/net.h, test/unit_test.c
See http://go.cesanta.com/bounded-read-buffers
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/272)
=> Implement bounded recv buffer

examples/arduino_restful_client/Makefile, examples/arduino_restful_client/arduino_restful_client.ino, examples/arduino_restful_server/arduino_restful_server.ino, examples/restful_server/restful_server.c, fossa.c, platforms/arduino_ethernet_W5100/avrsupport.cpp, platforms/arduino_ethernet_W5100/avrsupport.h, platforms/arduino_ethernet_W5100/src/W5100_sockets.cpp, platforms/arduino_ethernet_W5100/src/W5100_sockets.h, platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp, platforms/arduino_wifi_CC3000/src/CC3000_utils.h, src/net.c
Hi, @rojer 
Please review this PR.
In general, it contains restful_client example for W5100 and small changes to get it working.
Thanx.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/270)
=> Add Arduino example (restful_client/W5100)

scripts/docgen.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/274)
=> Ignore all private API on doc generation

examples/arduino_restful_client/arduino_restful_client.ino, platforms/Makefile, platforms/arduino_wifi_CC3000/Makefile, platforms/arduino_wifi_CC3000/adafruit_CC3000_lib_fossa/utility/socket.cpp, platforms/arduino_wifi_CC3000/avrsupport.cpp, platforms/arduino_wifi_CC3000/avrsupport.h, platforms/arduino_wifi_CC3000/src/CC3000_utils.cpp
This PR contains support of CC3000 for restful_client sample (and some changes to get it working).
Also, it contains an amalgamation (avrsupport.h &cpp) - I forget to add it into previous PR.
Note: my power supply unit was broken and CC3000 became unstable (BTW, it stated to work accordingly Adafruit FAQ). I have to add a couple of `delay` and surround some code with `#if 0` to stabilize it. These fixes marked as `/* TODO(alashkin): power fix */`.
I'll fix it as soon as I'll buy new psu (or repair mine).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/273)
=> Add CC3000 support in restful_client example

apps/load_balancer/load_balancer.c
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/277)
=> Use most specific URI prefix for load_balancer

fossa.c, src/net.c
now it works for the following DNS entries:
myserver.com IN CNAME mysecondserver.com
mysecondserver.com IN CNAME mythirdserver.com
mythirdserver.com IN A 8.8.8.8
didn't work before...
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/269)
=> fix: problem with resolve_cb and DNS CNAME entries

examples/arduino_restful_client/README.md, examples/arduino_restful_server/README.md
Hi, @cpq 
This is two short README.md for arduinos samples
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/278)
=> Add Arduino Examples readme

fossa.c, src/resolv.c
1) If the registry value is empty - check the next interface.
2) Return proper address from ns_get_ip_address_of_nameserver, not
just the IP (confusing naming is confusing).
While I'm here, remove ret--++ madness and make it obviously return
exactly what the documentation says.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/281)
=> Fix #176 for real

apps/load_balancer/Makefile, apps/load_balancer/load_balancer.c, platforms/arduino_wifi_CC3000/avrsupport.cpp, platforms/arduino_wifi_CC3000/avrsupport.h
Also factor log writing into a separate function.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/279)
=> Fix choose_backend() logic

fossa.h
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/cesanta/fossa/286)
=> Reamalgamate fossa.h after PR 285
